apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  WORDPRESS_DB_HOST: "wordpress-dev-mysql.c12okismevev.eu-central-1.rds.amazonaws.com"
  WORDPRESS_DB_USER: "wpuser"
  WORDPRESS_DB_PASSWORD: "StrongPassword123!"
  WORDPRESS_DB_NAME: "wordpress"