name: CI

on:
  push:
    branches:
      - main

jobs:

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/envs/dev

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan -lock=false


  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 \
          | docker login --username AWS --password-stdin \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t wordpress-dev:latest -f app/docker/Dockerfile ./app

      - name: Tag Docker image
        run: |
          docker tag wordpress-dev:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/wordpress-dev:latest

      - name: Push Docker image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/wordpress-dev:latest


  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region eu-central-1 \
            --name wordpress-dev-eks

      - name: Restart deployment
        run: |
          kubectl rollout restart deployment/wordpress -n wordpress

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/wordpress -n wordpress


  k8s:
    name: Kubernetes YAML validation
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y yamllint
      - run: yamllint k8s/
