name: Dev CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/envs/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infrastructure/envs/dev init -input=false

      - name: Terraform Validate
        run: terraform -chdir=infrastructure/envs/dev validate

      - name: Terraform Plan
        run: terraform -chdir=infrastructure/envs/dev plan -lock=false

  kubernetes:
    name: Kubernetes Manifest Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Validate manifests (client only)
        run: kubectl apply --dry-run=client --validate=false -f k8s/